openapi: 3.0.0
info:
  title: SynerPark
  version: '1.0'
  description: ''
servers:
  - url: 'http://synerpark.test/api'
    description: Local
paths:
  /cities:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/City'
                  meta:
                    type: object
                    properties:
                      pagination:
                        $ref: '#/components/schemas/Pagination'
      operationId: get-cities
      parameters:
        - schema:
            type: integer
          in: query
          name: page
components:
  schemas:
    City:
      title: City
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        state_name:
          type: string
        country_name:
          type: string
        region_name:
          type: string
        latitude:
          type: string
        longitude:
          type: string
    Pagination:
      title: Pagination
      type: object
      properties:
        total:
          type: integer
        count:
          type: integer
        per_page:
          type: integer
        current_page:
          type: integer
        total_pages:
          type: integer
